import { App, ConfigProvider } from "antd";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import React from "react";

import { GLOBAL_STYLE } from "@/style/theme";
import { I18nProvider } from "@/i18n";

import "jifou-react-ui/dist/index.css";
import "./globals.css";

const geist = Geist({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${geist.className} bg-background text-foreground overflow-hidden`}>
    <main>
      <AntdRegistry>
        <ConfigProvider theme={GLOBAL_STYLE}>
          <I18nProvider>
            <App className="size-screen" style={{ height: "100dvh" }}>
              {children}
            </App>
          </I18nProvider>
        </ConfigProvider>
      </AntdRegistry>
    </main>
    </body>
    </html>
  );
}
